java -jar compiler.jar --compilation_level WHITESPACE_ONLY \
--js=../public_html/OmegaTrick/src/app/Entry.js \
--js=../public_html/OmegaTrick/src/app/App.js \
--js=../public_html/OmegaTrick/src/widgets/SigninWindow.js \
--js=../public_html/OmegaTrick/src/plugins/DisplayFieldNumberFormat.js \
--js=../public_html/OmegaTrick/src/plugins/FocusActive.js \
--js=../public_html/OmegaTrick/src/util/Clone.js \
--js=../public_html/OmegaTrick/src/util/Phantom.js \
--js=../public_html/OmegaTrick/src/util/ScriptLoader.js \
--js=../public_html/OmegaTrick/src/widgets/form/FormPanel.js \
--js=../public_html/OmegaTrick/src/widgets/layout/ScreenLayout.js \
--js=../public_html/OmegaTrick/src/widgets/ScreenPanel.js \
--js=../public_html/OmegaTrick/src/core/Config.js \
--js=../public_html/OmegaTrick/src/core/String.js \
--js=../public_html/OmegaTrick/src/core/Ext.js \
--js_output_file=../public_html/OmegaTrick/OmegaTrick-all.js
